version: "3.9"

services:
  backend:
    build: .
    container_name: bogoballers-backend
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python run.py
    networks:
      - bogoballers-network

networks:
  bogoballers-network:
    external: true
