"""added entity id

Revision ID: 005091ff26ab
Revises: adeadaa9fbca
Create Date: 2025-09-06 18:17:54.891485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005091ff26ab'
down_revision: Union[str, Sequence[str], None] = 'adeadaa9fbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages_table', sa.Column('sender_entity_id', sa.String(), nullable=False))
    op.add_column('messages_table', sa.Column('receiver_entity_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages_table', 'receiver_entity_id')
    op.drop_column('messages_table', 'sender_entity_id')
    # ### end Alembic commands ###
