"""added is config

Revision ID: 05b03899e41a
Revises: c3ca87d20b66
Create Date: 2025-10-17 09:34:45.425585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b03899e41a'
down_revision: Union[str, Sequence[str], None] = 'c3ca87d20b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_round_format_table', sa.Column('is_configured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_round_format_table', 'is_configured')
    # ### end Alembic commands ###
