"""Add player id for league player for no team player compatability

Revision ID: 067f6988e69d
Revises: 71ee886e07ec
Create Date: 2025-09-05 11:40:14.320192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067f6988e69d'
down_revision: Union[str, Sequence[str], None] = '71ee886e07ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_players_table', sa.Column('player_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'league_players_table', 'players_table', ['player_id'], ['player_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_players_table', type_='foreignkey')
    op.drop_column('league_players_table', 'player_id')
    # ### end Alembic commands ###
