"""rename to obj

Revision ID: 08f1ebb7ec84
Revises: 594e8a21650d
Create Date: 2025-10-16 21:15:26.648698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08f1ebb7ec84'
down_revision: Union[str, Sequence[str], None] = '594e8a21650d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_round_format_table', sa.Column('format_obj', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'league_round_format_table', ['round_id'])
    op.drop_column('league_round_format_table', 'format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_round_format_table', sa.Column('format', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'league_round_format_table', type_='unique')
    op.drop_column('league_round_format_table', 'format_obj')
    # ### end Alembic commands ###
