"""init s

Revision ID: 09f5214fba39
Revises: 72184de5ebd3
Create Date: 2025-08-19 09:14:20.516763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f5214fba39'
down_revision: Union[str, Sequence[str], None] = '72184de5ebd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams_table', sa.Column('team_captain_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'teams_table', 'player_team_table', ['team_captain_id'], ['player_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams_table', type_='foreignkey')
    op.drop_column('teams_table', 'team_captain_id')
    # ### end Alembic commands ###
