"""added group label

Revision ID: 0b2ba110785a
Revises: 25ad585bb988
Create Date: 2025-09-23 21:03:03.401399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2ba110785a'
down_revision: Union[str, Sequence[str], None] = '25ad585bb988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('group_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_teams_table', 'group_label')
    # ### end Alembic commands ###
