"""added title

Revision ID: 12819b6c18fa
Revises: c5fc696e261e
Create Date: 2025-08-17 21:26:25.412858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12819b6c18fa'
down_revision: Union[str, Sequence[str], None] = 'c5fc696e261e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'league_teams_table', ['league_id'])
    op.add_column('notifications_table', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('teams_table_team_captain_id_fkey'), 'teams_table', type_='foreignkey')
    op.create_foreign_key(None, 'teams_table', 'player_team_table', ['team_captain_id'], ['player_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams_table', type_='foreignkey')
    op.create_foreign_key(op.f('teams_table_team_captain_id_fkey'), 'teams_table', 'player_team_table', ['team_captain_id'], ['player_team_id'], ondelete='SET NULL')
    op.drop_column('notifications_table', 'title')
    op.drop_constraint(None, 'league_teams_table', type_='unique')
    # ### end Alembic commands ###
