"""rename ban nanme

Revision ID: 17f608f6ab8b
Revises: 9e2b81e84aa7
Create Date: 2025-09-12 07:50:17.356429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f608f6ab8b'
down_revision: Union[str, Sequence[str], None] = '9e2b81e84aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_players_table', sa.Column('is_ban_in_league', sa.Boolean(), nullable=False))
    op.add_column('league_players_table', sa.Column('is_allowed_in_league', sa.Boolean(), nullable=False))
    op.drop_column('league_players_table', 'is_ban')
    op.drop_column('league_players_table', 'is_allowed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_players_table', sa.Column('is_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('league_players_table', sa.Column('is_ban', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('league_players_table', 'is_allowed_in_league')
    op.drop_column('league_players_table', 'is_ban_in_league')
    # ### end Alembic commands ###
