"""remove some timespamps

Revision ID: 1ca247e3c2af
Revises: cf1827e18028
Create Date: 2025-10-15 16:51:55.397208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ca247e3c2af'
down_revision: Union[str, Sequence[str], None] = 'cf1827e18028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_category_rounds_table', 'league_category_round_created_at')
    op.drop_column('league_category_rounds_table', 'league_category_round_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_category_rounds_table', sa.Column('league_category_round_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('league_category_rounds_table', sa.Column('league_category_round_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
