"""remove displaay names

Revision ID: 1d8644079f8a
Revises: ee6bcf88791e
Create Date: 2025-09-14 16:41:21.045020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8644079f8a'
down_revision: Union[str, Sequence[str], None] = 'ee6bcf88791e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_matches_table', 'display_name')
    op.drop_column('league_matches_table', 'generated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_matches_table', sa.Column('generated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('league_matches_table', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
