"""added per ovt

Revision ID: 1e1eb0a10230
Revises: 4b494415d609
Create Date: 2025-09-17 08:45:02.119279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1eb0a10230'
down_revision: Union[str, Sequence[str], None] = '4b494415d609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_matches_table', sa.Column('minutes_per_overtime', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_matches_table', 'minutes_per_overtime')
    # ### end Alembic commands ###
