"""remove unique

Revision ID: 218d2f73fc5f
Revises: a137cecf352b
Create Date: 2025-09-03 10:13:26.764497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218d2f73fc5f'
down_revision: Union[str, Sequence[str], None] = 'a137cecf352b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('league_teams_table_league_id_key'), 'league_teams_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('league_teams_table_league_id_key'), 'league_teams_table', ['league_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
