"""added group id

Revision ID: 238de0246286
Revises: 5f69618a6e8b
Create Date: 2025-11-27 19:39:07.738327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238de0246286'
down_revision: Union[str, Sequence[str], None] = '5f69618a6e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('league_team_group_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_teams_table', 'league_team_group_id')
    # ### end Alembic commands ###
