"""option automatic sdasd

Revision ID: 27f4a2e4f761
Revises: d90d03a4e3b6
Create Date: 2025-09-26 20:39:32.757723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f4a2e4f761'
down_revision: Union[str, Sequence[str], None] = 'd90d03a4e3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_categories_table', 'manage_automatic',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_categories_table', 'manage_automatic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
