"""add guest team fee

Revision ID: 29e3112239db
Revises: f713d5c84a05
Create Date: 2025-11-15 08:48:35.268006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e3112239db'
down_revision: Union[str, Sequence[str], None] = 'f713d5c84a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories_table', sa.Column('guest_team_fee_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories_table', 'guest_team_fee_amount')
    # ### end Alembic commands ###
