"""added check constraints

Revision ID: 2ce7c812bef8
Revises: 6e9f2a1dbd01
Create Date: 2025-10-07 13:01:38.611487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce7c812bef8'
down_revision: Union[str, Sequence[str], None] = '6e9f2a1dbd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_matches_table', 'generated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_matches_table', 'generated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
