"""added constaints

Revision ID: 2e8d561aaee2
Revises: 29e3112239db
Create Date: 2025-11-15 16:06:42.024243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8d561aaee2'
down_revision: Union[str, Sequence[str], None] = '29e3112239db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_final_per_category', 'league_matches_table', ['league_category_id'], unique=True, postgresql_where=sa.text('is_final = TRUE'))
    op.create_index('unique_runner_up_per_category', 'league_matches_table', ['league_category_id'], unique=True, postgresql_where=sa.text('is_runner_up = TRUE'))
    op.create_index('unique_third_place_per_category', 'league_matches_table', ['league_category_id'], unique=True, postgresql_where=sa.text('is_third_place = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_third_place_per_category', table_name='league_matches_table', postgresql_where=sa.text('is_third_place = TRUE'))
    op.drop_index('unique_runner_up_per_category', table_name='league_matches_table', postgresql_where=sa.text('is_runner_up = TRUE'))
    op.drop_index('unique_final_per_category', table_name='league_matches_table', postgresql_where=sa.text('is_final = TRUE'))
    # ### end Alembic commands ###
