"""asdasd

Revision ID: 32534e4ef409
Revises: 72220798fc8a
Create Date: 2025-09-26 13:01:42.841161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32534e4ef409'
down_revision: Union[str, Sequence[str], None] = '72220798fc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_groups_table', sa.Column('league_category_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'league_groups_table', 'league_categories_table', ['league_category_id'], ['league_category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_groups_table', type_='foreignkey')
    op.drop_column('league_groups_table', 'league_category_id')
    # ### end Alembic commands ###
