"""add doc table

Revision ID: 35744f0c89c3
Revises: d774aba43fc4
Create Date: 2025-10-31 09:33:48.958348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35744f0c89c3'
down_revision: Union[str, Sequence[str], None] = 'd774aba43fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_valid_documents',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players_table.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_valid_documents')
    # ### end Alembic commands ###
