"""Add relation to league player on league category

Revision ID: 3b9a5f2505de
Revises: 907a5dab1fe8
Create Date: 2025-09-05 11:00:33.881475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9a5f2505de'
down_revision: Union[str, Sequence[str], None] = '907a5dab1fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_players_table', sa.Column('league_category_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'league_players_table', 'league_categories_table', ['league_category_id'], ['league_category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_players_table', type_='foreignkey')
    op.drop_column('league_players_table', 'league_category_id')
    # ### end Alembic commands ###
