"""added league id

Revision ID: 3ba753219573
Revises: d9dd8220e16e
Create Date: 2025-10-08 08:03:17.310980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba753219573'
down_revision: Union[str, Sequence[str], None] = 'd9dd8220e16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_registration_requests_table', sa.Column('league_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'guest_registration_requests_table', 'leagues_table', ['league_id'], ['league_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guest_registration_requests_table', type_='foreignkey')
    op.drop_column('guest_registration_requests_table', 'league_id')
    # ### end Alembic commands ###
