"""added valid docs field in player

Revision ID: 3c8676bf64a1
Revises: 218d2f73fc5f
Create Date: 2025-09-03 21:54:14.364463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8676bf64a1'
down_revision: Union[str, Sequence[str], None] = '218d2f73fc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_table', sa.Column('valid_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players_table', 'valid_documents')
    # ### end Alembic commands ###
