"""asdasdsd

Revision ID: 3f08f33207ba
Revises: 
Create Date: 2025-09-11 23:31:31.893259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f08f33207ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_matches_table', sa.Column('league_match_updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('league_matches_table', 'round_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('league_matches_table', 'home_team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('league_matches_table', 'away_team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('league_matches_table_home_team_id_fkey'), 'league_matches_table', type_='foreignkey')
    op.drop_constraint(op.f('league_matches_table_away_team_id_fkey'), 'league_matches_table', type_='foreignkey')
    op.create_foreign_key(None, 'league_matches_table', 'league_teams_table', ['home_team_id'], ['league_team_id'])
    op.create_foreign_key(None, 'league_matches_table', 'league_teams_table', ['away_team_id'], ['league_team_id'])
    op.drop_column('league_matches_table', 'league_match_cupdated_at')
    op.drop_column('leagues_table', 'option')
    op.alter_column('matches_table', 'home_team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('matches_table', 'away_team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('matches_table_home_team_id_fkey'), 'matches_table', type_='foreignkey')
    op.drop_constraint(op.f('matches_table_away_team_id_fkey'), 'matches_table', type_='foreignkey')
    op.create_foreign_key(None, 'matches_table', 'teams_table', ['home_team_id'], ['team_id'])
    op.create_foreign_key(None, 'matches_table', 'teams_table', ['away_team_id'], ['team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches_table', type_='foreignkey')
    op.drop_constraint(None, 'matches_table', type_='foreignkey')
    op.create_foreign_key(op.f('matches_table_away_team_id_fkey'), 'matches_table', 'teams_table', ['away_team_id'], ['team_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('matches_table_home_team_id_fkey'), 'matches_table', 'teams_table', ['home_team_id'], ['team_id'], ondelete='SET NULL')
    op.alter_column('matches_table', 'away_team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('matches_table', 'home_team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('leagues_table', sa.Column('option', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('league_matches_table', sa.Column('league_match_cupdated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'league_matches_table', type_='foreignkey')
    op.drop_constraint(None, 'league_matches_table', type_='foreignkey')
    op.create_foreign_key(op.f('league_matches_table_away_team_id_fkey'), 'league_matches_table', 'league_teams_table', ['away_team_id'], ['league_team_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('league_matches_table_home_team_id_fkey'), 'league_matches_table', 'league_teams_table', ['home_team_id'], ['league_team_id'], ondelete='SET NULL')
    op.alter_column('league_matches_table', 'away_team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('league_matches_table', 'home_team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('league_matches_table', 'round_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('league_matches_table', 'league_match_updated_at')
    # ### end Alembic commands ###
