"""added no team uniquq constraints no team

Revision ID: 437a8fb3d76d
Revises: 067f6988e69d
Create Date: 2025-09-05 12:02:22.265563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437a8fb3d76d'
down_revision: Union[str, Sequence[str], None] = '067f6988e69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_player_no_team_league', 'league_players_table', ['league_id', 'player_id'])
    op.create_unique_constraint('uq_player_no_team_league_category', 'league_players_table', ['league_category_id', 'player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_player_no_team_league_category', 'league_players_table', type_='unique')
    op.drop_constraint('uq_player_no_team_league', 'league_players_table', type_='unique')
    # ### end Alembic commands ###
