"""remove title

Revision ID: 45c6b6b6b0c3
Revises: 005091ff26ab
Create Date: 2025-09-06 19:36:20.658737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c6b6b6b0c3'
down_revision: Union[str, Sequence[str], None] = '005091ff26ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages_table', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages_table', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
