"""added eliminated at

Revision ID: 4825ae5ec061
Revises: 0b2ba110785a
Create Date: 2025-09-23 21:50:44.544840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4825ae5ec061'
down_revision: Union[str, Sequence[str], None] = '0b2ba110785a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('eliminated_in_round_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'league_teams_table', 'league_category_rounds_table', ['eliminated_in_round_id'], ['round_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_teams_table', type_='foreignkey')
    op.drop_column('league_teams_table', 'eliminated_in_round_id')
    # ### end Alembic commands ###
