"""added field remove optional

Revision ID: 4b494415d609
Revises: 8b24858b4d91
Create Date: 2025-09-16 22:48:58.104763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b494415d609'
down_revision: Union[str, Sequence[str], None] = '8b24858b4d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_table', 'total_steals',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_table', 'total_blocks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_table', 'total_turnovers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_table', 'total_fg2_made',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_table', 'total_fg2_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_table', 'total_fg3_made',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_table', 'total_fg3_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_table', 'total_ft_made',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_table', 'total_ft_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_table', 'total_ft_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_table', 'total_ft_made',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_table', 'total_fg3_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_table', 'total_fg3_made',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_table', 'total_fg2_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_table', 'total_fg2_made',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_table', 'total_turnovers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_table', 'total_blocks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_table', 'total_steals',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
