"""added added is round robin

Revision ID: 4fd2e34977ed
Revises: 238de0246286
Create Date: 2025-11-27 20:36:01.715211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd2e34977ed'
down_revision: Union[str, Sequence[str], None] = '238de0246286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_matches_table', sa.Column('is_round_robin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_matches_table', 'is_round_robin')
    # ### end Alembic commands ###
