"""added staffsadasdasd super

Revision ID: 53ba19bad7c9
Revises: e8f4ddbb16f4
Create Date: 2025-12-11 17:56:28.943286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ba19bad7c9'
down_revision: Union[str, Sequence[str], None] = 'e8f4ddbb16f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_staff_table', sa.Column('is_super', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_staff_table', 'is_super')
    # ### end Alembic commands ###
