"""nullable ids

Revision ID: 546738b113f0
Revises: 2f21ac3ea960
Create Date: 2025-09-21 07:30:30.449044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546738b113f0'
down_revision: Union[str, Sequence[str], None] = '2f21ac3ea960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_matches_table', 'home_team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('league_matches_table', 'away_team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('unique_league_match_per_round'), 'league_matches_table', type_='unique')
    op.create_unique_constraint('unique_league_match_per_round', 'league_matches_table', ['league_id', 'league_category_id', 'round_number', 'stage_number', 'home_team_id', 'away_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_league_match_per_round', 'league_matches_table', type_='unique')
    op.create_unique_constraint(op.f('unique_league_match_per_round'), 'league_matches_table', ['league_id', 'league_category_id', 'round_number', 'home_team_id', 'away_team_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('league_matches_table', 'away_team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('league_matches_table', 'home_team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
