"""added option

Revision ID: 54f9ce1200b6
Revises: c60be50de155
Create Date: 2025-09-10 19:53:51.360256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54f9ce1200b6'
down_revision: Union[str, Sequence[str], None] = 'c60be50de155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_category_rounds_table', sa.Column('format_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_category_rounds_table', 'format_options')
    # ### end Alembic commands ###
