"""make nullable

Revision ID: 594e8a21650d
Revises: 1ca247e3c2af
Create Date: 2025-10-15 19:03:45.902947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594e8a21650d'
down_revision: Union[str, Sequence[str], None] = '1ca247e3c2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_round_format_table', 'round_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_round_format_table', 'round_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
