"""added new format league cat

Revision ID: 5f69618a6e8b
Revises: c430840537e8
Create Date: 2025-11-22 17:07:12.544798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f69618a6e8b'
down_revision: Union[str, Sequence[str], None] = 'c430840537e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_round_format_table', sa.Column('league_category_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'league_round_format_table', 'league_categories_table', ['league_category_id'], ['league_category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_round_format_table', type_='foreignkey')
    op.drop_column('league_round_format_table', 'league_category_id')
    # ### end Alembic commands ###
