"""add league team public id

Revision ID: 5f99c9aa2763
Revises: c35ca8ecb9d7
Create Date: 2025-09-22 06:27:16.015437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f99c9aa2763'
down_revision: Union[str, Sequence[str], None] = 'c35ca8ecb9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('league_team_public_id', sa.String(length=16), nullable=False))
    op.create_unique_constraint(None, 'league_teams_table', ['league_team_public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_teams_table', type_='unique')
    op.drop_column('league_teams_table', 'league_team_public_id')
    # ### end Alembic commands ###
