"""added new fields

Revision ID: 621cba5c06e5
Revises: 
Create Date: 2025-09-19 17:47:54.479375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621cba5c06e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_matches_table', sa.Column('depends_on_match_ids', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('league_matches_table', sa.Column('is_placeholder', sa.Boolean(), nullable=False))
    op.add_column('league_matches_table', sa.Column('bracket_stage_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_matches_table', 'bracket_stage_label')
    op.drop_column('league_matches_table', 'is_placeholder')
    op.drop_column('league_matches_table', 'depends_on_match_ids')
    # ### end Alembic commands ###
