"""added asdasd

Revision ID: 6a1aba6222ef
Revises: c8c7a5b96ca5
Create Date: 2025-12-04 14:51:41.427816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1aba6222ef'
down_revision: Union[str, Sequence[str], None] = 'c8c7a5b96ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_match_records_table', sa.Column('league_match_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'league_match_records_table', 'league_matches_table', ['league_match_id'], ['league_match_id'], ondelete='CASCADE')
    op.drop_column('league_match_records_table', 'record_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_match_records_table', sa.Column('record_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'league_match_records_table', type_='foreignkey')
    op.drop_column('league_match_records_table', 'league_match_id')
    # ### end Alembic commands ###
