"""added guest enum

Revision ID: 6e9f2a1dbd01
Revises: b4d2a0dcc8ef
Create Date: 2025-09-30 14:09:44.324626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9f2a1dbd01'
down_revision: Union[str, Sequence[str], None] = 'b4d2a0dcc8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest_registration_requests_table', 'payment_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Pending', 'Paid Online', 'Paid On Site', 'No Charge', 'Refunded', 'Partially Refunded', name='payment_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest_registration_requests_table', 'payment_status',
               existing_type=sa.Enum('Pending', 'Paid Online', 'Paid On Site', 'No Charge', 'Refunded', 'Partially Refunded', name='payment_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
