"""bring back two fields of league match

Revision ID: 71699b12ab9e
Revises: 1d8644079f8a
Create Date: 2025-09-14 17:31:17.676498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71699b12ab9e'
down_revision: Union[str, Sequence[str], None] = '1d8644079f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_matches_table', sa.Column('generated_by', sa.String(), nullable=True))
    op.add_column('league_matches_table', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_matches_table', 'display_name')
    op.drop_column('league_matches_table', 'generated_by')
    # ### end Alembic commands ###
