"""Add unique constraints to league player in the category

Revision ID: 71ee886e07ec
Revises: 3b9a5f2505de
Create Date: 2025-09-05 11:08:27.919066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ee886e07ec'
down_revision: Union[str, Sequence[str], None] = '3b9a5f2505de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_league_category_player', 'league_players_table', ['league_category_id', 'player_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_league_category_player', 'league_players_table', type_='unique')
    # ### end Alembic commands ###
