"""Add unique constraint team per league

Revision ID: 71f9e253de35
Revises: 3c8676bf64a1
Create Date: 2025-09-05 08:42:50.412415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f9e253de35'
down_revision: Union[str, Sequence[str], None] = '3c8676bf64a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_team_per_league', 'league_teams_table', ['team_id', 'league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_per_league', 'league_teams_table', type_='unique')
    # ### end Alembic commands ###
