"""asdasddassad

Revision ID: 72220798fc8a
Revises: a092165c17c4
Create Date: 2025-09-26 11:49:54.922972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72220798fc8a'
down_revision: Union[str, Sequence[str], None] = 'a092165c17c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('league_teams_table_eliminated_in_round_id_fkey'), 'league_teams_table', type_='foreignkey')
    op.create_foreign_key(None, 'league_teams_table', 'league_category_rounds_table', ['eliminated_in_round_id'], ['round_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_teams_table', type_='foreignkey')
    op.create_foreign_key(op.f('league_teams_table_eliminated_in_round_id_fkey'), 'league_teams_table', 'league_category_rounds_table', ['eliminated_in_round_id'], ['round_id'])
    # ### end Alembic commands ###
