"""init ai model

Revision ID: 73306916c78e
Revises: ca0a9175a49e
Create Date: 2025-11-12 15:44:33.394167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73306916c78e'
down_revision: Union[str, Sequence[str], None] = 'ca0a9175a49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversation_table',
    sa.Column('convo_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message_role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('convo_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('convo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_conversation_table')
    # ### end Alembic commands ###
