"""round name as enum

Revision ID: 79c2f902d5e0
Revises: 2e8d561aaee2
Create Date: 2025-11-15 20:48:49.470907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c2f902d5e0'
down_revision: Union[str, Sequence[str], None] = '2e8d561aaee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_category_rounds_table', 'round_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Elimination', 'Quarterfinal', 'Semifinal', 'Final', name='round_name_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_category_rounds_table', 'round_name',
               existing_type=sa.Enum('Elimination', 'Quarterfinal', 'Semifinal', 'Final', name='round_name_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
