"""added current stage

Revision ID: 8387bb341bf0
Revises: 05b03899e41a
Create Date: 2025-10-17 16:36:46.370419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8387bb341bf0'
down_revision: Union[str, Sequence[str], None] = '05b03899e41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_category_rounds_table', sa.Column('current_stage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_category_rounds_table', 'current_stage')
    # ### end Alembic commands ###
