"""added jsonb to payment record

Revision ID: 88868f069155
Revises: 068ee3caae8a
Create Date: 2025-09-08 12:47:38.132427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88868f069155'
down_revision: Union[str, Sequence[str], None] = '068ee3caae8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('payment_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_teams_table', 'payment_record')
    # ### end Alembic commands ###
