"""add two fields

Revision ID: 896f422cee67
Revises: c54c9584f8ef
Create Date: 2025-09-14 08:30:28.407870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896f422cee67'
down_revision: Union[str, Sequence[str], None] = 'c54c9584f8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('final_rank', sa.Integer(), nullable=True))
    op.add_column('league_teams_table', sa.Column('is_champion', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_teams_table', 'is_champion')
    op.drop_column('league_teams_table', 'final_rank')
    # ### end Alembic commands ###
