"""added fields

Revision ID: 8b24858b4d91
Revises: 71699b12ab9e
Create Date: 2025-09-16 22:43:32.982737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b24858b4d91'
down_revision: Union[str, Sequence[str], None] = '71699b12ab9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_table', sa.Column('total_steals', sa.Integer(), nullable=True))
    op.add_column('players_table', sa.Column('total_blocks', sa.Integer(), nullable=True))
    op.add_column('players_table', sa.Column('total_turnovers', sa.Integer(), nullable=True))
    op.add_column('players_table', sa.Column('total_fg2_made', sa.Integer(), nullable=True))
    op.add_column('players_table', sa.Column('total_fg2_attempts', sa.Integer(), nullable=True))
    op.add_column('players_table', sa.Column('total_fg3_made', sa.Integer(), nullable=True))
    op.add_column('players_table', sa.Column('total_fg3_attempts', sa.Integer(), nullable=True))
    op.add_column('players_table', sa.Column('total_ft_made', sa.Integer(), nullable=True))
    op.add_column('players_table', sa.Column('total_ft_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players_table', 'total_ft_attempts')
    op.drop_column('players_table', 'total_ft_made')
    op.drop_column('players_table', 'total_fg3_attempts')
    op.drop_column('players_table', 'total_fg3_made')
    op.drop_column('players_table', 'total_fg2_attempts')
    op.drop_column('players_table', 'total_fg2_made')
    op.drop_column('players_table', 'total_turnovers')
    op.drop_column('players_table', 'total_blocks')
    op.drop_column('players_table', 'total_steals')
    # ### end Alembic commands ###
