"""adsdsd

Revision ID: 8cb0a1a741ca
Revises: bb66395c837f
Create Date: 2025-12-05 10:53:25.134117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cb0a1a741ca'
down_revision: Union[str, Sequence[str], None] = 'bb66395c837f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leagues_table', 'league_objective',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('leagues_table', 'league_rationale',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leagues_table', 'league_rationale',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('leagues_table', 'league_objective',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
