"""Add unique constraint in league player model

Revision ID: 907a5dab1fe8
Revises: 71f9e253de35
Create Date: 2025-09-05 10:08:41.701664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907a5dab1fe8'
down_revision: Union[str, Sequence[str], None] = '71f9e253de35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_league_player', 'league_players_table', ['league_id', 'player_team_id'])
    op.create_unique_constraint('uq_league_team_player', 'league_players_table', ['league_team_id', 'player_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_league_team_player', 'league_players_table', type_='unique')
    op.drop_constraint('uq_league_player', 'league_players_table', type_='unique')
    # ### end Alembic commands ###
