"""remvoe is runner up

Revision ID: 9d6b068b487f
Revises: 79c2f902d5e0
Create Date: 2025-11-16 09:42:06.865922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6b068b487f'
down_revision: Union[str, Sequence[str], None] = '79c2f902d5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_matches_table', 'is_runner_up')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_matches_table', sa.Column('is_runner_up', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
