"""option automaticdsads

Revision ID: 9e1c598ab08f
Revises: 27f4a2e4f761
Create Date: 2025-09-27 07:59:37.651936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1c598ab08f'
down_revision: Union[str, Sequence[str], None] = '27f4a2e4f761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('verification_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'verification_token')
    # ### end Alembic commands ###
