"""remove is ban

Revision ID: 9e2b81e84aa7
Revises: 3f08f33207ba
Create Date: 2025-09-12 07:48:20.864752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2b81e84aa7'
down_revision: Union[str, Sequence[str], None] = '3f08f33207ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_team_table', 'is_ban')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_team_table', sa.Column('is_ban', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
