"""asdasddas

Revision ID: a092165c17c4
Revises: cde54ae50bbd
Create Date: 2025-09-26 10:41:24.228376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a092165c17c4'
down_revision: Union[str, Sequence[str], None] = 'cde54ae50bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_flow_edges_table',
    sa.Column('edge_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.String(), nullable=False),
    sa.Column('source_handle', sa.String(), nullable=True),
    sa.Column('target_handle', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues_table.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_flow_edges_table')
    # ### end Alembic commands ###
