"""added valid docs in category

Revision ID: a137cecf352b
Revises: 6437ef3cac0b
Create Date: 2025-09-01 22:59:43.191505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a137cecf352b'
down_revision: Union[str, Sequence[str], None] = '6437ef3cac0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories_table', sa.Column('requires_valid_document', sa.Boolean(), nullable=False))
    op.add_column('categories_table', sa.Column('allowed_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('categories_table', sa.Column('document_valid_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories_table', 'document_valid_until')
    op.drop_column('categories_table', 'allowed_documents')
    op.drop_column('categories_table', 'requires_valid_document')
    # ### end Alembic commands ###
