"""team stamping

Revision ID: a9d6838ae3a1
Revises: f88bfdd05611
Create Date: 2025-09-12 10:34:39.544534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9d6838ae3a1'
down_revision: Union[str, Sequence[str], None] = 'f88bfdd05611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('league_team_created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('league_teams_table', sa.Column('league_team_updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('league_teams_table', 'created_at')
    op.drop_column('league_teams_table', 'updated_at')
    op.add_column('teams_table', sa.Column('team_created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('teams_table', sa.Column('team_updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('teams_table', 'created_at')
    op.drop_column('teams_table', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams_table', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('teams_table', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('teams_table', 'team_updated_at')
    op.drop_column('teams_table', 'team_created_at')
    op.add_column('league_teams_table', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('league_teams_table', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('league_teams_table', 'league_team_updated_at')
    op.drop_column('league_teams_table', 'league_team_created_at')
    # ### end Alembic commands ###
