"""added sender and receiver name

Revision ID: adeadaa9fbca
Revises: 014a7eea80c9
Create Date: 2025-09-06 17:56:02.643061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adeadaa9fbca'
down_revision: Union[str, Sequence[str], None] = '014a7eea80c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages_table', sa.Column('sender_name', sa.String(length=255), nullable=False))
    op.add_column('messages_table', sa.Column('receiver_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages_table', 'receiver_name')
    op.drop_column('messages_table', 'sender_name')
    # ### end Alembic commands ###
