"""added format config

Revision ID: ae1db24f36f4
Revises: c903ad870dae
Create Date: 2025-09-09 14:42:45.536315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae1db24f36f4'
down_revision: Union[str, Sequence[str], None] = 'c903ad870dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_category_rounds_table', sa.Column('format_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('league_category_rounds_table', 'round_format')
    op.drop_column('matches_table', 'format_config')
    op.drop_column('matches_table', 'match_format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches_table', sa.Column('match_format', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('matches_table', sa.Column('format_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('league_category_rounds_table', sa.Column('round_format', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('league_category_rounds_table', 'format_config')
    # ### end Alembic commands ###
