"""added staff

Revision ID: b3eb3b58e8aa
Revises: 8cb0a1a741ca
Create Date: 2025-12-11 10:14:36.747190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3eb3b58e8aa'
down_revision: Union[str, Sequence[str], None] = '8cb0a1a741ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_staff_table',
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=False),
    sa.Column('assigned_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('league_administrator_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_administrator_id'], ['league_administrator_table.league_administrator_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('username')
    )
    op.drop_index(op.f('idx_match_scheduled_date'), table_name='league_matches_table')
    op.drop_index(op.f('idx_team_updated_date'), table_name='league_teams_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_team_updated_date'), 'league_teams_table', ['league_id', sa.literal_column("((league_team_updated_at AT TIME ZONE 'UTC'::text)::date)")], unique=False)
    op.create_index(op.f('idx_match_scheduled_date'), 'league_matches_table', ['league_id', sa.literal_column("((scheduled_date AT TIME ZONE 'UTC'::text)::date)")], unique=False)
    op.drop_table('league_staff_table')
    # ### end Alembic commands ###
