"""added guest

Revision ID: b4d2a0dcc8ef
Revises: 46034bed8e79
Create Date: 2025-09-30 14:09:07.481389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4d2a0dcc8ef'
down_revision: Union[str, Sequence[str], None] = '46034bed8e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_registration_requests_table',
    sa.Column('guest_request_id', sa.String(), nullable=False),
    sa.Column('league_category_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('request_type', sa.Enum('Team', 'Player', name='guest_request_type_enum'), nullable=False, comment="Specifies whether the request is for a 'Team' or a 'Player'."),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Rejected', name='guest_request_status_enum'), nullable=False, comment='The current status of the request (Pending, Accepted, Rejected).'),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_processed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the request was accepted or rejected.'),
    sa.CheckConstraint("(request_type = 'Team' AND team_id IS NOT NULL AND player_id IS NULL) OR (request_type = 'Player' AND player_id IS NOT NULL AND team_id IS NULL)", name='chk_guest_request_entity'),
    sa.ForeignKeyConstraint(['league_category_id'], ['league_categories_table.league_category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players_table.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams_table.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guest_request_id'),
    sa.UniqueConstraint('league_category_id', 'player_id', name='uq_guest_player_request'),
    sa.UniqueConstraint('league_category_id', 'team_id', name='uq_guest_team_request')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_registration_requests_table')
    # ### end Alembic commands ###
