"""added match_generated

Revision ID: b73a26626283
Revises: 77a7ea546ba3
Create Date: 2025-09-10 10:04:01.559241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73a26626283'
down_revision: Union[str, Sequence[str], None] = '77a7ea546ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_category_rounds_table', sa.Column('matches_generated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_category_rounds_table', 'matches_generated')
    # ### end Alembic commands ###
