"""bring back team category

Revision ID: b759ed166f4a
Revises: efc753e49012
Create Date: 2025-08-29 23:10:08.162606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b759ed166f4a'
down_revision: Union[str, Sequence[str], None] = 'efc753e49012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams_table', sa.Column('team_category', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams_table', 'team_category')
    # ### end Alembic commands ###
