"""addadasdasd

Revision ID: b9179ea53a9e
Revises: f999dea20c82
Create Date: 2025-12-05 07:30:50.176458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9179ea53a9e'
down_revision: Union[str, Sequence[str], None] = 'f999dea20c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_administrator_table', 'organization_country',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('league_administrator_table', 'organization_province',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('league_administrator_table', 'organization_municipality',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_administrator_table', 'organization_municipality',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('league_administrator_table', 'organization_province',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('league_administrator_table', 'organization_country',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
