"""added format table

Revision ID: bab7a42dcc3f
Revises: 3d1995df43a5
Create Date: 2025-10-15 11:33:51.600295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bab7a42dcc3f'
down_revision: Union[str, Sequence[str], None] = '3d1995df43a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_round_format_table',
    sa.Column('format_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('format_name', sa.String(), nullable=False),
    sa.Column('format', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['league_category_rounds_table.round_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('format_id')
    )
    op.drop_column('league_category_rounds_table', 'format_type')
    op.drop_column('league_category_rounds_table', 'round_format')
    op.drop_column('league_category_rounds_table', 'format_config')
    op.drop_column('league_category_rounds_table', 'format_options')
    op.drop_column('league_groups_table', 'league_group_created_at')
    op.drop_column('league_groups_table', 'league_group_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_groups_table', sa.Column('league_group_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('league_groups_table', sa.Column('league_group_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('league_category_rounds_table', sa.Column('format_options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('league_category_rounds_table', sa.Column('format_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('league_category_rounds_table', sa.Column('round_format', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('league_category_rounds_table', sa.Column('format_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('league_round_format_table')
    # ### end Alembic commands ###
