"""adsd

Revision ID: bb66395c837f
Revises: b9179ea53a9e
Create Date: 2025-12-05 10:49:46.084215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb66395c837f'
down_revision: Union[str, Sequence[str], None] = 'b9179ea53a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues_table', sa.Column('league_objective', sa.String(length=500), nullable=True))
    op.add_column('leagues_table', sa.Column('league_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues_table', 'league_rationale')
    op.drop_column('leagues_table', 'league_objective')
    # ### end Alembic commands ###
