"""added added is round robinds

Revision ID: bd36d72f67ca
Revises: 4fd2e34977ed
Create Date: 2025-11-27 20:49:39.835895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd36d72f67ca'
down_revision: Union[str, Sequence[str], None] = '4fd2e34977ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_matches_table', 'is_round_robin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_matches_table', 'is_round_robin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
