"""added format type

Revision ID: c3ca87d20b66
Revises: 08f1ebb7ec84
Create Date: 2025-10-17 05:53:39.961958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ca87d20b66'
down_revision: Union[str, Sequence[str], None] = '08f1ebb7ec84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_round_format_table', sa.Column('format_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_round_format_table', 'format_type')
    # ### end Alembic commands ###
