"""added log model

Revision ID: c430840537e8
Revises: 
Create Date: 2025-11-21 19:38:19.434761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c430840537e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_logs_table',
    sa.Column('league_log_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=True),
    sa.Column('round_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('log_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues_table.league_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['league_category_rounds_table.round_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['league_teams_table.league_team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_logs_table')
    # ### end Alembic commands ###
