"""add finalize_at at table

Revision ID: c54c9584f8ef
Revises: a9d6838ae3a1
Create Date: 2025-09-14 08:24:45.638659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54c9584f8ef'
down_revision: Union[str, Sequence[str], None] = 'a9d6838ae3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('finalized_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_teams_table', 'finalized_at')
    # ### end Alembic commands ###
