"""init tablessds

Revision ID: c5fc696e261e
Revises: e985da339e86
Create Date: 2025-08-17 21:09:41.608980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fc696e261e'
down_revision: Union[str, Sequence[str], None] = 'e985da339e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams_table', sa.Column('team_captain_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'teams_table', 'player_team_table', ['team_captain_id'], ['player_team_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams_table', type_='foreignkey')
    op.drop_column('teams_table', 'team_captain_id')
    # ### end Alembic commands ###
