"""added is eliminated

Revision ID: c60be50de155
Revises: b73a26626283
Create Date: 2025-09-10 18:59:31.666738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60be50de155'
down_revision: Union[str, Sequence[str], None] = 'b73a26626283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_teams_table', sa.Column('is_eliminated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_teams_table', 'is_eliminated')
    # ### end Alembic commands ###
