"""added league address

Revision ID: c8353bc6463d
Revises: 09f5214fba39
Create Date: 2025-08-24 21:24:14.554608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8353bc6463d'
down_revision: Union[str, Sequence[str], None] = '09f5214fba39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leagues_table', 'league_title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.drop_index(op.f('idx_players_full_text'), table_name='players_table', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_players_full_text'), 'players_table', [sa.literal_column("to_tsvector('english'::regconfig, (((full_name::text || ' '::text) || jersey_name::text) || ' '::text) || player_address::text)")], unique=False, postgresql_using='gin')
    op.alter_column('leagues_table', 'league_title',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
