"""asd

Revision ID: c8c7a5b96ca5
Revises: d2ac7c7a411e
Create Date: 2025-12-03 23:44:56.837229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8c7a5b96ca5'
down_revision: Union[str, Sequence[str], None] = 'd2ac7c7a411e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_match_records_table',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('record_name', sa.String(length=250), nullable=False),
    sa.Column('record_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues_table.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.drop_table('league_records_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_records_table',
    sa.Column('record_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('record_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('record_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('record_id', name=op.f('league_records_table_pkey'))
    )
    op.drop_table('league_match_records_table')
    # ### end Alembic commands ###
