"""fix notification

Revision ID: c903ad870dae
Revises: 735ee7f35077
Create Date: 2025-09-08 18:43:12.930286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c903ad870dae'
down_revision: Union[str, Sequence[str], None] = '735ee7f35077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_table', sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('notifications_table_from_id_fkey'), 'notifications_table', type_='foreignkey')
    op.drop_column('notifications_table', 'action_id')
    op.drop_column('notifications_table', 'from_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_table', sa.Column('from_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications_table', sa.Column('action_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notifications_table_from_id_fkey'), 'notifications_table', 'users_table', ['from_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('notifications_table', 'action_payload')
    # ### end Alembic commands ###
