"""renameadsasd

Revision ID: ca0a9175a49e
Revises: e5aedd15ccec
Create Date: 2025-10-31 10:14:30.700965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca0a9175a49e'
down_revision: Union[str, Sequence[str], None] = 'e5aedd15ccec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_valid_documents_table', sa.Column('document_format', sa.String(length=20), nullable=False))
    op.drop_column('players_table', 'valid_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_table', sa.Column('valid_documents', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('player_valid_documents_table', 'document_format')
    # ### end Alembic commands ###
