"""asdasd

Revision ID: cde54ae50bbd
Revises: 4825ae5ec061
Create Date: 2025-09-26 10:38:32.969689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cde54ae50bbd'
down_revision: Union[str, Sequence[str], None] = '4825ae5ec061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_groups_table',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('league_group_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('league_group_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['league_category_rounds_table.round_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.add_column('league_categories_table', sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('league_matches_table', sa.Column('group_id', sa.String(), nullable=True))
    op.add_column('league_matches_table', sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'league_matches_table', 'league_groups_table', ['group_id'], ['group_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_matches_table', type_='foreignkey')
    op.drop_column('league_matches_table', 'position')
    op.drop_column('league_matches_table', 'group_id')
    op.drop_column('league_categories_table', 'position')
    op.drop_table('league_groups_table')
    # ### end Alembic commands ###
