"""rename

Revision ID: d2ac7c7a411e
Revises: fdb6efa51ba3
Create Date: 2025-12-03 23:09:07.924933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2ac7c7a411e'
down_revision: Union[str, Sequence[str], None] = 'fdb6efa51ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_records_table',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('record_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.drop_table('records_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_table',
    sa.Column('record_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('record_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('record_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('record_id', name=op.f('records_table_pkey'))
    )
    op.drop_table('league_records_table')
    # ### end Alembic commands ###
