"""option automatic

Revision ID: d90d03a4e3b6
Revises: cfd8bf96bb04
Create Date: 2025-09-26 20:38:04.510411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90d03a4e3b6'
down_revision: Union[str, Sequence[str], None] = 'cfd8bf96bb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_categories_table', sa.Column('manage_automatic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_categories_table', 'manage_automatic')
    # ### end Alembic commands ###
