"""asdasdsd

Revision ID: e331cbd9bd4e
Revises: 32534e4ef409
Create Date: 2025-09-26 14:11:37.037097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e331cbd9bd4e'
down_revision: Union[str, Sequence[str], None] = '32534e4ef409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_flow_edges_table', sa.Column('league_category_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'league_flow_edges_table', 'league_categories_table', ['league_category_id'], ['league_category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_flow_edges_table', type_='foreignkey')
    op.drop_column('league_flow_edges_table', 'league_category_id')
    # ### end Alembic commands ###
