"""rename

Revision ID: e5aedd15ccec
Revises: 35744f0c89c3
Create Date: 2025-10-31 09:35:22.397267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5aedd15ccec'
down_revision: Union[str, Sequence[str], None] = '35744f0c89c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_valid_documents_table',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players_table.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.drop_table('player_valid_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_valid_documents',
    sa.Column('doc_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_urls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players_table.player_id'], name=op.f('player_valid_documents_player_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id', name=op.f('player_valid_documents_pkey'))
    )
    op.drop_table('player_valid_documents_table')
    # ### end Alembic commands ###
