"""added staffsadas

Revision ID: e735b01c6b2a
Revises: b3eb3b58e8aa
Create Date: 2025-12-11 10:45:06.598378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e735b01c6b2a'
down_revision: Union[str, Sequence[str], None] = 'b3eb3b58e8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_staff_table', sa.Column('pin_hash', sa.String(), nullable=False))
    op.add_column('league_staff_table', sa.Column('staff_created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('league_staff_table', sa.Column('staff_updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('league_staff_table', 'updated_at')
    op.drop_column('league_staff_table', 'created_at')
    op.drop_column('league_staff_table', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_staff_table', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('league_staff_table', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('league_staff_table', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('league_staff_table', 'staff_updated_at')
    op.drop_column('league_staff_table', 'staff_created_at')
    op.drop_column('league_staff_table', 'pin_hash')
    # ### end Alembic commands ###
