"""asdasdsds

Revision ID: e8d09a3dcae6
Revises: e331cbd9bd4e
Create Date: 2025-09-26 20:36:05.080991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d09a3dcae6'
down_revision: Union[str, Sequence[str], None] = 'e331cbd9bd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_category_rounds_table', sa.Column('manage_automatic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_category_rounds_table', 'manage_automatic')
    # ### end Alembic commands ###
