"""added staffsadasdasasd

Revision ID: e8f4ddbb16f4
Revises: 56aa63b756ee
Create Date: 2025-12-11 12:53:02.044071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f4ddbb16f4'
down_revision: Union[str, Sequence[str], None] = '56aa63b756ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_staff_table', sa.Column('full_name', sa.String(length=250), nullable=False))
    op.add_column('league_staff_table', sa.Column('contact_info', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'league_staff_table', ['contact_info'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_staff_table', type_='unique')
    op.drop_column('league_staff_table', 'contact_info')
    op.drop_column('league_staff_table', 'full_name')
    # ### end Alembic commands ###
