"""init

Revision ID: ea84a291c920
Revises: 
Create Date: 2025-09-28 08:54:56.551673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea84a291c920'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_categories_table', 'league_category_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Close', 'Open', 'Ongoing', 'Completed', name='league_category_status_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_categories_table', 'league_category_status',
               existing_type=sa.Enum('Close', 'Open', 'Ongoing', 'Completed', name='league_category_status_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
