"""added league address final

Revision ID: ed4db8e177dd
Revises: c8353bc6463d
Create Date: 2025-08-24 21:25:20.453629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4db8e177dd'
down_revision: Union[str, Sequence[str], None] = 'c8353bc6463d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues_table', sa.Column('league_address', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues_table', 'league_address')
    # ### end Alembic commands ###
