"""remove is exisbision

Revision ID: edc712f05075
Revises: 5f99c9aa2763
Create Date: 2025-09-23 06:58:51.101741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc712f05075'
down_revision: Union[str, Sequence[str], None] = '5f99c9aa2763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_matches_table', 'is_exhibition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_matches_table', sa.Column('is_exhibition', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
