"""sadadsdsdsdsds

Revision ID: efc753e49012
Revises: 58f239007e98
Create Date: 2025-08-28 22:10:51.000812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc753e49012'
down_revision: Union[str, Sequence[str], None] = '58f239007e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_table', 'total_join_league',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_table', 'total_join_league',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
