"""remove duplicate league_id from league_players_table

Revision ID: f587c3ea8dce
Revises: 54f9ce1200b6
Create Date: 2025-09-11 08:57:12.797764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f587c3ea8dce'
down_revision: Union[str, Sequence[str], None] = '54f9ce1200b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
