"""created enumssadasd

Revision ID: f713d5c84a05
Revises: d87a896467ed
Create Date: 2025-11-12 15:47:22.228720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f713d5c84a05'
down_revision: Union[str, Sequence[str], None] = 'd87a896467ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_conversation_table', 'message_role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('user', 'coach', name='ai_basketball_mentor_role_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_conversation_table', 'message_role',
               existing_type=sa.Enum('user', 'coach', name='ai_basketball_mentor_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
