"""rename ban nanme remove unique

Revision ID: f88bfdd05611
Revises: 17f608f6ab8b
Create Date: 2025-09-12 10:03:26.330712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88bfdd05611'
down_revision: Union[str, Sequence[str], None] = '17f608f6ab8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('leagues_table_league_administrator_id_key'), 'leagues_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('leagues_table_league_administrator_id_key'), 'leagues_table', ['league_administrator_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
