"""addadasd

Revision ID: f999dea20c82
Revises: 6a1aba6222ef
Create Date: 2025-12-05 07:27:34.837818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f999dea20c82'
down_revision: Union[str, Sequence[str], None] = '6a1aba6222ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_administrator_table', sa.Column('organization_country', sa.String(length=250), nullable=True))
    op.add_column('league_administrator_table', sa.Column('organization_province', sa.String(length=250), nullable=True))
    op.add_column('league_administrator_table', sa.Column('organization_municipality', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_administrator_table', 'organization_municipality')
    op.drop_column('league_administrator_table', 'organization_province')
    op.drop_column('league_administrator_table', 'organization_country')
    # ### end Alembic commands ###
