"""added records table

Revision ID: fdb6efa51ba3
Revises: bd36d72f67ca
Create Date: 2025-12-03 23:08:23.118791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdb6efa51ba3'
down_revision: Union[str, Sequence[str], None] = 'bd36d72f67ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_table',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('record_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records_table')
    # ### end Alembic commands ###
